version: '0.1'

services:
 efm-mocks:
   build: .
   image: eformidling/efm-mocks

extends: 
  template: build-and-deploy-template.yml@efm-eproc-pipeline
  parameters: 
    preDockerComposePush:
      - task: Bash@3
        displayName: Running mocks integration tests
        inputs:
          targetType: inline
          workingDirectory: .
          script: | 
          sh pipeline.sh