version: '3.2'
services:
  mocks:
    restart: unless-stopped
    build: ./mocks
    command: npm run start
    environment:
      DPI_HOST: ${DPI_HOST}
    ports:
      - ${MOCK_PORT}:${MOCK_PORT}

  sa-mock:
    restart: unless-stopped
    build: ./move-sakarkiv-mock
    command: npm run start
    environment:
      IP_URL: ${IP_URL}
    ports:
      - ${SA_MOCK_PORT}:${SA_MOCK_PORT}

  wiremock:
    restart: unless-stopped
    build: ./Wiremock
    ports:
      - ${WIREMOCK_PORT}:${WIREMOCK_PORT}

  dpimock:
    restart: unless-stopped
    build: ./dpimock
    command:  cd ./dpimock && ./mvnw install dockerfile:build
    ports:
      - ${DPI_PORT}:8080
  ip:
    restart: unless-stopped
    build: ./ip
    environment:
      IP_PORT: 9094
    ports:
      - ${IP_PORT}:9097
      - 9097:9093
  # ip_local:
  #   environment:
  #     IP_PORT: 9099
  #   restart: unless-stopped
  #   build: ./ip_local
  #   ports:
  #     - ${IP_PORT}:9093
      #- 9097:9093